package com.example.Database.query;

public enum QueryType {
    CREATE_DATABASE,
    READ_DATABASES,
    DELETE_DATABASE,
    CREATE_COLLECTION,
    READ_COLLECTIONS,
    DELETE_COLLECTION,
    CREATE_DOCUMENT,
    READ_DOCUMENTS,
    SEARCH,
    UPDATE_DOCUMENT_PROPERTY,
    DELETE_DOCUMENT
}